# Generated by Django 2.0.4 on 2019-07-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0003_auto_20190702_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowconf',
            name='customfield',
            field=models.TextField(verbose_name='自定义字段'),
        ),
        migrations.AlterField(
            model_name='flowconf',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
    ]
