# Generated by Django 2.0.4 on 2019-07-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0004_auto_20190702_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoActionConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptpath', models.CharField(max_length=64, verbose_name='脚本路径')),
                ('url', models.URLField(max_length=64, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='NewFlowUserRoleActionConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=64, verbose_name='审批序号')),
                ('approvetorole', models.CharField(max_length=64, verbose_name='是否角色组审批')),
                ('approve_type_id', models.CharField(max_length=64, verbose_name='审批类型')),
                ('is_auto', models.BooleanField(default=False, verbose_name='是否自动化')),
                ('flowconf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workOrder.FlowConf')),
            ],
        ),
        migrations.AddField(
            model_name='autoactionconf',
            name='flowconf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workOrder.NewFlowUserRoleActionConf'),
        ),
    ]
