# Generated by Django 2.0.4 on 2019-07-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0005_auto_20190702_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newflowuserroleactionconf',
            name='approvetorole',
            field=models.BooleanField(default=False, verbose_name='是否角色组审批'),
        ),
    ]
