# Generated by Django 2.0.4 on 2019-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0007_auto_20190703_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoactionconf',
            name='scriptpath',
        ),
        migrations.AddField(
            model_name='autoactionconf',
            name='time',
            field=models.CharField(default='', max_length=64, verbose_name='超时时间'),
        ),
    ]
