# Generated by Django 2.0.4 on 2019-07-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0008_auto_20190703_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoactionconf',
            old_name='time',
            new_name='timeout',
        ),
    ]
