# Generated by Django 2.0.4 on 2019-07-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0010_auto_20190705_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suborder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subordercallbacklog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workordercallbacklog',
            options={},
        ),
    ]
