# Generated by Django 2.0.4 on 2019-07-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0012_auto_20190705_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowconf',
            name='callback',
            field=models.CharField(max_length=64, null=True, verbose_name='回调地址'),
        ),
    ]
