# Generated by Django 2.0.4 on 2019-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0013_auto_20190705_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordercallbacklog',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
