# Generated by Django 2.0.4 on 2019-07-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0014_auto_20190705_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subordercallbacklog',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
