# Generated by Django 2.0.4 on 2019-07-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0015_auto_20190705_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='subordercallbacklog',
            name='method2',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
