# Generated by Django 2.0.4 on 2019-07-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0016_subordercallbacklog_method2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subordercallbacklog',
            name='method2',
        ),
    ]
