# Generated by Django 2.0.4 on 2019-07-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0017_remove_subordercallbacklog_method2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subordercallbacklog',
            name='sub_order',
        ),
        migrations.DeleteModel(
            name='SubOrderCallbacklog',
        ),
    ]
