# Generated by Django 2.0.4 on 2019-07-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0020_suborder_approvetorole'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='dispose_user',
            field=models.IntegerField(blank=True, null=True, verbose_name='处理后用户id'),
        ),
    ]
